#!/bin/sh
setxkbmap dvorak

# probably instead of caps = rubout, caps = alt!??
#xmodmap ~/keys/xmodmap_symbolics
#xmodmap ~/keys/xmodmap_rubout

xmodmap ~/keys/xmodmap_swap-caps-ctrl

# problem with xmonad's workspace switching :(
#xmodmap ~/keys/xmodmap_swap-numbers-symbols
xmodmap ~/keys/xmodmap_umlauts-functions

# make caps_lock => rubout repeatable
xset r 66
