#!/bin/sh
setxkbmap dvorak

xmodmap ~/keys/xmodmap_symbolics
xmodmap ~/keys/xmodmap_swap-numbers-symbols
xmodmap ~/keys/xmodmap_umlauts
xmodmap ~/keys/xmodmap_rubout

# make caps_lock => rubout repeatable
xset r 66
